source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'WLCardViewLayout_Example' do
  pod 'WLCardViewLayout', :path => '../'
end

target 'WLCardViewLayout_Tests' do
  pod 'WLCardViewLayout', :path => '../'

  
end
